//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [Serializable]
    [DataContract]
    public partial class apartamento
    {
        public apartamento()
        {
            this.morador = new HashSet<morador>();
        }

        [DataMember]
        public int id { get; set; }
        [DataMember]
        public string numero { get; set; }
        [DataMember]
        public string bloco { get; set; }
    
        public virtual ICollection<morador> morador { get; set; }
    }
}
