//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [Serializable]
    [DataContract]
    public partial class morador
    {
        [DataMember]
        public int id { get; set; }
        [DataMember]
        public string nome { get; set; }
        [DataMember]
        public string cpf { get; set; }
        [DataMember]
        public string email { get; set; }
        [DataMember]
        public Nullable<System.DateTime> data_nascimento { get; set; }
        [DataMember]
        public string telefone { get; set; }
        [DataMember]
        public Nullable<int> id_apartamento { get; set; }
    
        public virtual apartamento apartamento { get; set; }
    }
}
